### PR TITLE
Initial stub

### PR DESCRIPTION
**Pull request by karolyi**
Can we get some typing going? See the issue https://github.com/microsoft/pyright/issues/3848

### CODE REVIEW

**Comment by karolyi** [comment]
bump

**Comment by karolyi** [comment]
bump?

**Comment by benjaoming** [comment]
@karolyi thanks for opening this, I believe the right place to discuss the change is in https://github.com/django-money/django-money/issues/677 - I unfortunately can't contribute much to the discussion.

**Comment by karolyi** [comment]
Alright, I now have fixed the typing and the CI error. I have no idea why the automatic CI run isn't triggered.

It should be ready to be merged now.

**Comment by benjaoming** [comment]
@karolyi GitHub has introduced a new security level for CIs so builds aren't run from unknown contributors

image

**Comment by karolyi** [comment]
@benjaoming I see, thanks. Not a welcome change I guess.

I have no idea why the tests are erroring out, but I think it's not because of my changes. The most I could take away from the logs is that there is a `DeprecationWarning: pkg_resources is deprecated as an API` which makes the entire pipeline fail, even though the tests are passing.

Suggestions are welcome.

**Comment by karolyi** [comment]
Okay, I've dug up a bit more about this. Upon looking at the reason why `DeprecationWarning`s are errors, I've found https://github.com/django-money/django-money/commit/d992a25d that introduced it. It also added ignoring specific errors so I took the courage and added this specific warning that results in an error, as an ignored one.

It should work now. I hope my efforts are not in vain.

**Comment by benjaoming** [comment]
> @benjaoming I see, thanks. Not a welcome change I guess.

As a default for new repos, it could make sense... but seeing that it wasn't used in existing repos, you could think that those repos already run a risk-free CI. But maybe it's also saving a lot of CI computation for Microsoft, which I guess is fair.. at least good for the environment :)

> It should work now. I hope my efforts are not in vain.

No, I think this is perfect! Thanks for looking into it and fixing it! I'm fine merging such a fix as part of another PR.

**Review by benjaoming — APPROVED** [review]
Tests are working, fixes to CI, this is a great PR, thanks @karolyi !

**Comment by karolyi** [comment]
Thank you! Now I'm hoping for a timely release. :)

**Pull request merged**
