### PR TITLE
Added Django 1.10 support. Closes #198.

### LINKED ISSUE #198: Django 1.10 support

### PR DESCRIPTION
**Pull request by Stranger6667**
Works for Django 1.10a1 & master branch.

### CODE REVIEW

**Comment by benjaoming** [comment]
Oh cool! Maybe add a django1.10.x tox configuration?

**Comment by benjaoming** [comment]
Looks good, if it passes, merge I guess :)

**Comment by Stranger6667** [comment]
Ok! I'll add it after some little fix

**Comment by benjaoming** [comment]
I can't see that the Codecov reported coverage decrease is reflect in their own reports. It says all changes are 100% covered.

**Comment by Stranger6667** [comment]
Seems like a bug in Codecov :(

**Comment by benjaoming** [comment]
Agree! Otherwise this is ready? :)

**Comment by Stranger6667** [comment]
Yes

**Pull request merged**
