### PR TITLE
Fix invalid flake8 repository

### LINKED ISSUE #696: pre-commit is trying to get flake8 from Gitlab
I would like to do my first contribution to this project. Unfortunately, I cannot run the `tox -e lint,django111-py36,django111-py27` command because pre-commit is trying to download flake8 from this repository: https://gitlab.com/pycqa/flake8. Because of that, I see the prompt to provide Gitlab credentials. Anyway, I tried to open the repository in Gitlab, but it doesn't exist (maybe it's private).

### Steps to reproduce

1. Fork and clone the project
2. Install requirements
3. Run `tox -e lint,django111-py36,django111-py27`

### Proposal
I propose to use the flake8 Github repository: https://github.com/pycqa/flake8.

### PR DESCRIPTION
**Pull request by sdarmofal**
Switch from Gitlab to GitHub flake8 repository in pre-commit-config.yaml .

Closes #696

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
Thanks!

Feels like I've fixed that a million places :+1: 

Seems to never end :hamster: :ferris_wheel:

**Comment by sdarmofal** [comment]
@benjaoming There is another problem - with tox. Probably dots in the section substitution cause the problem. I've pushed the fix for it but please take a look once again :)

**Comment by sdarmofal** [comment]
@benjaoming Just a kind reminder :)

**Comment by benjaoming** [comment]
@sdarmofal there are some build failures, could you have a look? :)

**Comment by sdarmofal** [comment]
I found that Django dropped support for Python versions lower than 3.10 on the main branch. Hope my change helps :)

**Comment by benjaoming** [comment]
Thanks for looking into this @sdarmofal ! It seems this PR has caught your arm rather than your finger :)

**Comment by benjaoming** [comment]
The GitHub action matrix also needs a quick similar update to align with tox.ini :/

**Comment by sdarmofal** [comment]
@benjaoming Good catch. I'll fix it too :)

**Comment by sdarmofal** [comment]
I don't know if you're getting notifications about pushes to PRs. If not - I've updated the GitHub workflow

**Review by benjaoming — COMMENTED** [review]
@sdarmofal no that seems to be an issue here. I get notifications of commits normally, though. I'll try to add a review, that might be the reason.

**Comment by benjaoming** [comment]
Thanks for solving all this @sdarmofal :)

**Pull request merged**
