### PR TITLE
Fallback to _meta.fields if _meta.get_fields raises AttributeError fixes #149

### LINKED ISSUE #149: Model._meta.get_fields is only present in Django>=1.8
In the serializers.py there is a following line:

```
 field_names = set(f.name for f in Model._meta.get_fields())
```

This code will not work unless Django is >= 1.8 and therefore one cannot load any fixtures in Django < 1.8

Could this line possibly be replaced by following?

```
field_names = set(f.name for f in Model._meta.fields)
```

cheers,
toudi

### PR DESCRIPTION
**Pull request by browniebroke**
For projects using with Django < 1.8

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks, too bad no tests caught this :(

**Comment by slafs** [comment]
Thank you for this. Is there a chance for a new "bugfix" release anytime soon?

**Comment by benjaoming** [comment]
@reinbach there's a request for you presence, I think it sounds legit to do a bug fix release for this purpose!

**Comment by reinbach** [comment]
@benjaoming tagged the release and pushed to pypi

**Comment by benjaoming** [comment]
hurray!!! :D

**Comment by slafs** [comment]
Awesome! Thank you! :)

**Pull request merged**
