### PR TITLE
Fix bug where you cannot print a MoneyField

### PR DESCRIPTION
**Pull request by YAmikep**
See the following issue: https://github.com/django-money/django-money/issues/124

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks for this! Looks good! Did you happen to search through the code base for any similar patterns?

**Comment by YAmikep** [comment]
Yes I think it's good to go.
Any chance you will release a new version on pypi soon?
Thanks

**Comment by benjaoming** [comment]
I don't know maybe if @reinbach has time? :)

**Comment by reinbach** [comment]
@YAmikep @benjaoming 0.7.1 has been released... yay!

**Comment by benjaoming** [comment]
Hurray!!! @reinbach so happy I've added a badge in the readme :) https://github.com/django-money/django-money/blob/master/README.md

**Pull request merged**
