### PR TITLE
Cleanup release notes

### PR DESCRIPTION
**Pull request by benjaoming**
Getting rid of a recurring annoyance :)

@Stranger6667 can you have a look at the Read the Docs builds? I think that PR builds are inactive, but I can't seem to reactivate them. I think it's the OAuth authentication between RTD and GitHub that's tied to another account from mine, perhaps yours?

### CODE REVIEW

**Comment by Stranger6667** [comment]
I've updated GH settings, so the `pull_request` event is enabled now - my understanding is that RTD requires this event to build docs. Now, I guess that pushing here again should trigger the build on the RTD side.

**Comment by benjaoming** [comment]
Should I try to re-push?

**Comment by Stranger6667** [comment]
Yep, now everything should be fine

**Comment by Stranger6667** [comment]
I just re-connected my GH account to RTD and the docs build seems to be reported to a PR of a different project, so, the next force push should trigger them here too.

**Comment by Stranger6667** [comment]
Yep, it is here!

**Comment by benjaoming** [comment]
Yes, indeed :clap:

**Pull request merged**
