### PR TITLE
[WIP] Added Django REST Framework support. Closes #179

### LINKED ISSUE #179: Django REST Framework support
I propose to add `MoneyField` for Django REST Framework. It can be a useful feature IMO.
E.g.

```python
from rest_framework import serializers
from djmoney.extra.drf import MoneyField

class AccountSerializer(serializers.ModelSerializer):
    amount = MoneyField()

```

And `Money` instances will be de/serialized properly. Also I think it is possible to register this `MoneyField` directly in `ModelSerializer. serializer_field_mapping `, but I'm not sure about it for now.

I'll try to submit PR for that

### PR DESCRIPTION
**Pull request by Stranger6667**
I temporary removed autoconversion import from module-level. It is related to #199

### CODE REVIEW

**Comment by benjaoming** [comment]
Trying to get #207 to work and be merged in, could you rebase onto master once it's in? (having Travis issues atm)

**Comment by Stranger6667** [comment]
yes, no problem :)

**Comment by LordBastor** [comment]
@benjaoming Any chance the DRF support pull request will be merged any time soon?

Sorry for being *that guy*

I'm just using an ugly hack in my serializers and checking daily for an update via pip install.

**Comment by benjaoming** [comment]
@LordBastor but it is merged? :)

**Comment by LordBastor** [comment]
@benjaoming I feel like the biggest, blindest fool on the planet.

You have my sincerest apologies.

**Comment by Stranger6667** [comment]
But anyway, only in 0.9.1 DRF support is available, because I messed with packaging :( I don't know if it is already on PyPI

**Comment by reinbach** [comment]
0.9.1 has been released to pypi

**Pull request merged**
