### PR TITLE
Fixed access to models properties. Fixes #297

### LINKED ISSUE #297: using factory_boy with MoneyField gives Attribute Error
I have a `Transaction` model which uses a `MoneyField`. While writing tests, I realised that creating a test transaction object using the std django orm way via Transaction.objects.create() etc works ok but using factory_boy to create the same doesn't. Please help me out if I'm going about this wrong.

This is my model:
```
class Transaction(Timestampable, models.Model):
    amount = MoneyField(decimal_places=2, max_digits=10, default_currency='INR')
    # todo - default currency should be picked from profile/person
    # note2self - as of now a tx can have a single associated category but multiple tags are possible
    category = models.ForeignKey(Category, related_name="category_transactions", blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name="tag_transactions")  # also optional
    created_by = models.ForeignKey(Person, related_name="transactions")
    transaction_date = models.DateField()
    transaction_time = models.TimeField(blank=True, null=True)
```

This is the simplified factory and other code
```
class MoneyProvider(BaseProvider):
     def money(self):
        return Money(563, INR)

fake = Faker()
fake.add_provider(MoneyProvider)

class TransactionFactory(factory.DjangoModelFactory):
    """
        Factory used to instantiate class Transaction
        """

    class Meta:
        model = Transaction

    created_by = factory.SubFactory(PersonFactory)
    amount = fake.money()
    transaction_date = fake.date_time_between(start_date='-3d').date()
    transaction_time = None

    tags = None
    category = None
```
This is my test file

```
class TestTransactionModel(TestCase):
    def setUp(self):
        self.transaction = TransactionFactory.create(amount=Money(563, INR))
        # self.transaction = Transaction.objects.create(
        #     amount=Money(563, INR),
        #     created_by=PersonFactory.create(),
        #     transaction_date=timezone.now().date()
        # )

    def tearDown(self):
        self.transaction.delete()

    def test_something(self):
        pass
```
On running this i get 

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E.
======================================================================
ERROR: test_something (doubloon.transactions.tests.test_models.TestTransactionModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/myrtle/03_django_projects/doubloon/doubloon/transactions/tests/test_models.py", line 13, in setUp
    self.transaction = TransactionFactory.create(amount=Money(563, INR))
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/base.py", line 623, in create
    return cls._generate(True, attrs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/base.py", line 548, in _generate
    obj = cls._prepare(create, **attrs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/base.py", line 523, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/django.py", line 181, in _create
    return manager.create(*args, **kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/base.py", line 559, in __init__
    property_names = opts._property_names
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/options.py", line 890, in _property_names
    dir(self.model) if isinstance(getattr(self.model, attr), property)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/options.py", line 890, in <setcomp>
    dir(self.model) if isinstance(getattr(self.model, attr), property)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/djmoney/models/fields.py", line 225, in __get__
    raise AttributeError('Can only be accessed via an instance.')
AttributeError: Can only be accessed via an instance.
```
What am i doing wrong?

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by benjaoming** [comment]
Great with the fix! Once the tests are running, we can merge and get a patch release out!

**Comment by Stranger6667** [comment]
I've added tag 0.11.1 in branch 0.11.x.

**Comment by benjaoming** [comment]
> I've added tag 0.11.1 in branch 0.11.x and everything is ready to new release 

You didn't bump the version though ;)

**Comment by benjaoming** [comment]
It's done! Two small things for releasing:

 * Remember to bump the version :)
 * Sign the tag `git tag -s 0.x.y`

I've removed the old tag and added a new one + edited the release.

Also, I've started putting .tar.gz on PyPi again after realizing that a lot is still dependent on this, for instance downstream package maintainers use these.

**Comment by Stranger6667** [comment]
I bumped it in 0.11.x branch ... I assumed, that master branch would be 0.12.dev0

**Comment by Stranger6667** [comment]
But anyway dropping support for old Django versions will not affect many users with upgrading to djmoney 0.11.1 :) So, I'll fix the changelog this weekend

**Comment by Stranger6667** [comment]
Also, thanks for the release tips :) I'll do signing next time

**Comment by benjaoming** [comment]
> I bumped it in 0.11.x branch ...

Garh, I didn't even know we had a release tracking branch :)

**Comment by benjaoming** [comment]
Of course if I'd read my console more carefully...

screenshot from 2017-05-26 16-00-22

**Pull request merged**
