### PR TITLE
Add support for py-moneyed 1.x

### LINKED ISSUE #567: Support most recent changes in py-moneyed for formatting
In [py-moneyed](https://github.com/limist/py-moneyed) we have just merged a change that deprecates `moneyed.localization` in favour of `moneyed.l10n`. The latter contains a single, new `format_money` function, which simply delegates to [Babel number formatting functions](https://babel.pocoo.org/en/latest/api/numbers.html). This fixes many long-standing issues in our formatting, and frees us of the need to try to manually define all the different formats - we get them from Babel, which is based on [CLDR](http://cldr.unicode.org/) data.

Before releasing a new version of `py-moneyed`, I'd like to check that the new API works for django-money, since I know it is a major user of py-moneyed. Would it be possible for you to do an experimental branch that doesn't use `moneyed.localization` at all (or at least, only as a fallback)?

Please see the [new docs](https://py-moneyed.readthedocs.io/en/latest/formatting.html) and [CHANGES.rst](https://github.com/limist/py-moneyed/blob/master/CHANGES.rst)

Thanks.

### PR DESCRIPTION
**Pull request by antonagestam**
Closes #567

### CODE REVIEW

**Review by Stranger6667 — APPROVED** [review]
Wow! LGTM! :) Thank you!

**Comment by Stranger6667** [comment]
I'll add a changelog entry and will issue a new release :)

**Comment by Stranger6667** [comment]
Oh, It seems like ``currency_digits`` isn't yet there - I will check the details tomorrow.

**Comment by antonagestam** [comment]
@Stranger6667 You can set `currency_digits` and the other new options through `formatting_options`, so either of these:

```python
# in settings.py
MONEY_FORMAT = {
    "currency_digits": 3,
}

# in instantiation
Money(12.34, USD, format_options={"currency_digits": 3})
```

My intention with that is that we can add a `FormatOptions` TypedDict when adding type hints further on to get typing of the options. That type could also be exposed so that you could do:

```python
MONEY_FORMAT = FormatOptions(currency_digits=3)
```

**Comment by antonagestam** [comment]
Should have added that to the description here, had a bit of lag between implementing and opening the PR ;)

**Pull request merged**
