### PR TITLE
[WIP] Release 0.12.2

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by Stranger6667** [comment]
Hello @benjaoming !
Can we issue a new release? I prepared everything (hope so) for that

**Comment by benjaoming** [comment]
LGTM!

I think in the future, it's probably easier to target PRs straight to the lowest release branch that they're going into. You can change the target branch on contributor's PRs here:

image

On top of that, doing routine merges to sync `master` with all the release branches. It's a bit of manual work, but it's easier than picking commits from `master` to go into a release branch?

**Comment by benjaoming** [comment]
0.12.2 is released on PyPi :)

**Comment by Stranger6667** [comment]
Thank you! 
Agree, this approach looks cleaner, and more structured :)

**Pull request merged**
