### PR TITLE
Add support for money descriptor customization

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by benjaoming** [comment]
Other things you are planning in this PR?

**Comment by Stranger6667** [comment]
Hello Ben :) maybe some docs to illustrate possible use cases

**Comment by Stranger6667** [comment]
I think we can merge it now to include 2 features into `0.15.1` release :)

**Comment by benjaoming** [comment]
Ah, okay, just a reminder that `master` isn't targeted for 0.15 anymore.

**Pull request merged**
