### PR TITLE
Fix tox environment

### PR DESCRIPTION
**Pull request by edwinlunando**
add latest pymoneyed to tox environment. cc @benjaoming

### CODE REVIEW

**Comment by benjaoming** [comment]
Oh cool, I'll be checking back in shortly to see how this fares.. could you also merge in #114 so we can see how it tests out with tox configured for 1.8 ?

**Comment by edwinlunando** [comment]
guys, the test is not compatible with Django 1.8. Django has dropped django.test.simple.

**Comment by benjaoming** [comment]
@edwinlunando have you merged in #114 ? I don't know how much it takes care of...

**Comment by edwinlunando** [comment]
@benjaoming alright, the travis has run. there are some errors on the test. I will check it later.

**Comment by edwinlunando** [comment]
@benjaoming the test for Django 1.8 will be different from Django 1.4 and 1.5. Do we want to drop the support or use python six? I recommend we only support the current supported Django version.

**Comment by benjaoming** [comment]
@edwinlunando that's not a recommendation I back up... the only way to allow people to run flexible systems and have painless transitions between different django versions is to release django applications that are compatible with several versions of django.

**Comment by edwinlunando** [comment]
allright, I will use Python six then.

**Comment by benjaoming** [comment]
Awesome :)

**Comment by edwinlunando** [comment]
@benjaoming while I'm working on the test, do you mind looking into this error. I think it is a bug https://travis-ci.org/django-money/django-money/jobs/61447801

**Comment by benjaoming** [comment]
@edwinlunando no sorry, my involvement only goes as far as to review and merge stuff :) I maintain, I don't dev :)

**Comment by briankung** [comment]
@edwinlunando have you seen https://github.com/django-money/django-money/issues/101? **"Appends _currency to non-money ExpressionFields"**

**Pull request merged**
