### PR TITLE
Assert that it's possible to have DEFAULT_CURRENCY=None and a nullable MoneyField

### PR DESCRIPTION
**Pull request by benjaoming**
#490

CC: @washeck - would this work?

### CODE REVIEW

**Comment by washeck** [comment]
@benjaoming Yes, this looks perfect to me. Thank you.

**Comment by Stranger6667** [comment]
Sorry, I didn't see that it is against `0.14.x` :( Is it intended to be like this?

@benjaoming

**Comment by benjaoming** [comment]
> Is it intended to be like this?

Yeah, I wanted it like this because it behaves like a bug fix.. otherwise, it'd have to wait for 1.0 :)

**Comment by benjaoming** [comment]
Ah okay, let's wait until 1.0 then and not kick around this older branch :+1:

**Comment by benjaoming** [comment]
Added a release note

**Pull request merged**
