### PR TITLE
Version bump + pre-commit hooks

### PR DESCRIPTION
**Pull request by benjaoming**

### CODE REVIEW

**Comment by benjaoming** [comment]
@Stranger6667 once this is tested, would you mind skimming through it and comment if you see anything problematic? :) Everything is auto-generated. I thought we should have pre-commit hooks available in the repo, but they're not yet enforced in the .travis config

**Comment by Stranger6667** [comment]
LGTM! :+1: 
Pre-commit hooks are useful :)

**Comment by benjaoming** [comment]
@reinbach would you do the honours and release 0.7.7? I've already bumped the version in the codebase :)

**Comment by Stranger6667** [comment]
@benjaoming @reinbach , please, consider #177 before publishing new release :)

**Comment by benjaoming** [comment]
That's now merged :) Thanks!

**Pull request merged**
