### PR TITLE
Support for Django 1.9b1

### PR DESCRIPTION
**Pull request by kjagiello**

### CODE REVIEW

**Comment by benjaoming** [comment]
Great contribution -- Sorry for the stupid question, but have you run the tests manually for Django 1.9?

**Comment by kjagiello** [comment]
Not a stupid question at all! I've just committed fixes for the test suite and everything seems to be fine now.

**Comment by benjaoming** [comment]
Excellent work! :) All lights green, test config updated for 1.9, merging! :+1:

**Comment by benjaoming** [comment]
@reinbach perhaps a candidate for a release and version bump?

**Comment by reinbach** [comment]
@benjaoming version bumped (0.7.4) and release made

**Comment by benjaoming** [comment]
Fantastic! :) @kjagiello you changes are now installable with pip.

**Comment by kjagiello** [comment]
:beers:

**Pull request merged**
