### PR TITLE
fixing integration with DRF

### PR DESCRIPTION
**Pull request by hosamhamdy258**
Added requirements for integration with DRF on README
added default currency to fix Decimal object has no attribute amount on DRF classes

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
This makes sense to me. I'm not using DRF and I think that the other maintainer @Stranger6667 is in that same boat?

But I'll happily take you word that this is tested and works.. gonna run the integrations now...

**Comment by benjaoming** [comment]
Btw if the integrations fail, could you merge in the latest `main` as we've fixed a couple of things?

**Review by Stranger6667 — APPROVED** [review]
The changes look reasonable to me! Thank you :)

**Review by benjaoming — CHANGES_REQUESTED** [review]
@hosamhamdy258 after the tests have run, it seems like there is a related error. Would you be able to look into that+

**Comment by hosamhamdy258** [comment]
am fairly new contribute if someone can fix that issue as i can't do it myself now

**Comment by benjaoming** [comment]
@hosamhamdy258 details are in the failed test runs. I think you need to apply the new setting to relevant test settings.

**Comment by benjaoming** [comment]
@hosamhamdy258 there have been a few bug fixes in the `main` branch so you can try merging it into your forked `main` branch to see if you can progress?

**Comment by hosamhamdy258** [comment]
i found new solution after some digging i will create new PR

**Comment by benjaoming** [comment]
That sounds great! PR absolutely welcome :pray:

**Pull request closed without merging**
