### PR TITLE
Improved djmoney_rates support. Closes #173

### LINKED ISSUE #173: Django doesn't run then django-money-rates is installed but doesn't added to INSTALLED_APPS
I've added `djmoney` to INSTALLED_APPS.
I've installed `django-money-rates` package with pip into the same virtualenv  but I don't add `djmoney_rates` to INSTALLED_APPS (actually I use this virtualenv with different project branches and configurations).

When I execute any django managemement command (`manage.py --help` for example), 
then I get a trace:
```
...
  File "/opt/project/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/project/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/project/env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/project/env/lib/python2.7/site-packages/djmoney/models/__init__.py", line 3, in <module>
    serializers.register_serializer("json", 'djmoney.serializers')
  File "/opt/project/env/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 71, in register_serializer
    module = importlib.import_module(serializer_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/project/env/lib/python2.7/site-packages/djmoney/serializers.py", line 10, in <module>
    from djmoney.models.fields import MoneyField
  File "/opt/project/env/lib/python2.7/site-packages/djmoney/models/fields.py", line 32, in <module>
    from djmoney_rates.utils import convert_money
  File "/opt/project/env/lib/python2.7/site-packages/djmoney_rates/utils.py", line 5, in <module>
    from .models import Rate, RateSource
  File "/opt/project/env/lib/python2.7/site-packages/djmoney_rates/models.py", line 34, in <module>
    class RateSource(models.Model):
  File "/opt/project/env/lib/python2.7/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class djmoney_rates.models.RateSource doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```
I expect the manage.py should run then django-money-rates package is installed but `djmoney_rates` doesn't added to INSTALLED_APPS.

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by benjaoming** [comment]
Nice!

Not sure about the issue, but could you maybe open it upstream so they know? I didn't find an issue specifically mentioning dj 1.9... https://github.com/django-money/django-money/issues

**Comment by Stranger6667** [comment]
There is [PR](https://github.com/evonove/django-money-rates/pull/11) for that, but unfortunately there is no activity for last 2 years :(

**Comment by benjaoming** [comment]
Garh, that's exactly why Github sucks... dictators building projects, not communities and then when they leave, the community can't get stuff merged even if it does exist :(

**Comment by Stranger6667** [comment]
May be its worthable to merge it directly to django-money as a part of future release? Or may be forking of djmoney_rates is more preferable?

**Comment by benjaoming** [comment]
Dunno, how do you view the codebase of the project? Is it healthy and maintainable?

**Comment by benjaoming** [comment]
License should be compatible:

https://github.com/evonove/django-money-rates/blob/master/LICENSE

Maybe it could live in `djmoney.contrib` ?

**Comment by Stranger6667** [comment]
At first glance it seems healthy. But `dmoney_rates` has stricter Django support (1.5.1 - 1.8) and no mentions of Python versions other than 2.7 and 3.3. So, I can't guarantee that everything will be fine with that package.
Also there is an option to re-implement rates support in much simpler way for example for **0.8** release? What do you think about it? Then we will have full control on rates behavior inside `django-money`

**Comment by benjaoming** [comment]
As long as it's non-mandatory! If you isolate it in `djmoney.contrib.rates` then it will look like it's optional. Reimplementing it might be a bit drastic? But if you think it can be simplified and there is a lot to gain?

**Comment by benjaoming** [comment]
But the project seems dead, so if it's supposed to work for dj 1.9+, I would think the best choice would be to import it into django-money because this project is slightly more versatile :)

**Pull request merged**
