### PR TITLE
Migrate to Github Actions

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by Stranger6667** [comment]
I am going to merge this to roll out a new release :) Sorry for not discussing much stuff here, but I hope we can do it retrospectively if needed! cc @benjaoming

**Comment by benjaoming** [comment]
Can I share a hypothesis? It's great that you got things working! It's ALSO a nice example of how Microsoft's take-over of Github works: Get Travis out of the way and control all the CI services, as with their main competitor GitLab already showed was possible.

**Comment by Stranger6667** [comment]
> Get Travis out of the way and control all the CI services,

I am inclined to think that it mostly comes from Travis's post-acquisition layoffs & OSS cuts initiated by their new owner - Idera.  Travis's performance degraded significantly - I was waiting for CI jobs for 4 hours in one of django-money's PRs :( I'd be happy to see Travis CI competing with Github Actions in terms of convenience & features, rather than working vs. not-working.

But, as you said, it illustrates the current movements in the CI landscape. I interested in how do you feel regarding this change? Is there something we can do in terms of CI?

**Comment by benjaoming** [comment]
I didn't fully understand Travis initial reactions to Github disrupting their services with some newly imposed API limit: https://jamescooke.info/travis-hitting-githubs-api-limits-for-open-source-projects.html -- but you are right, it seems absolutely evident now that Travis was going to cut OSS anyways, and in a very ugly way.

We're dependent on CI, no doubt. The only thing I can imagine is a more self-hosted CI movement. Jenkins is not so nice to self-host, but drone.io is looking very promising. I can imagine that Open Source foundations and cooperatives could benefit from wrestling this infrastructure back from Microsoft -- seems problematic to have 100% of Open Source hosted by Microsoft (and Amazon hosts PyPi AFAIK).

If Travis taught us a lesson, it should be that "freemium" is _ALWAYS_ temporary, right until we discover how the business plan works.

**Comment by benjaoming** [comment]
But not suggesting anything from this particular project! Can be better to slipstream a larger ship.

**Pull request merged**
