### PR TITLE
Drop support for legacy versions

### PR DESCRIPTION
**Pull request by antonagestam**
- Drop support for Django 1.11, 2.1 and 3.0.
- Drop support for Python 3.5.
- Add support for Django 3.2.

### CODE REVIEW

**Review by Stranger6667 — CHANGES_REQUESTED** [review]
There is also version info in `README.rst` and [setup.py](https://github.com/django-money/django-money/blob/master/setup.py#L84). Could you, please, update it as well?

**Comment by antonagestam** [comment]
@Stranger6667 Oops, I missed those. I pushed a fixing commit 🙂

**Review by Stranger6667 — APPROVED** [review]
Great! I am thinking whether it makes sense to add support for `pymoneyed==1.x` before dropping support for unsupported Python / Django versions. This way, users on these versions may upgrade and use `babel`-powered formatting through `pymoneyed` without upgrading the rest from e.g. Django 1.11. What do you think?

**Comment by antonagestam** [comment]
@Stranger6667 I would have definitely gone the other way and not go out of my way to build stuff for unsupported versions, I tend to think about it as cleaning up the kitchen before starting making dinner ;) **But**, I'm not the maintainer here and I'll go along in the direction you set. In this particular case, it might not be much extra work either way.

Btw, I bumped into an issue with upgrading the formatting, I'll post the details on that issue.

**Comment by benjaoming** [comment]
@Stranger6667 sounds like a reasonable little intermediate release. Could that be added and released through a separate PR?

**Comment by antonagestam** [comment]
@benjaoming For reference, there's been discussion about that [here](https://github.com/django-money/django-money/issues/567) 🙂 I'm thinking this PR can stay open until a new version is released with support for py-moneyed 1.x.

**Comment by antonagestam** [comment]
@Stranger6667 @benjaoming Hi 👋 I've started working on the final step in the plan laid out, and [upgrading to py-moneyed 2.0](https://github.com/antonagestam/django-money/pull/1). Is there any chance to get this PR merged?

**Comment by Stranger6667** [comment]
@antonagestam Hi! I'll take a look during the weekend :)

**Comment by antonagestam** [comment]
Another thing for discussion here though, it would make sense to me also drop support for Python 3.6 now as it only has 3 more months to live, and probably even less by the time we're ready to release. It makes sense to me since we're about to make a major release anyway for py-moneyed 2. Wdyt?

**Comment by Stranger6667** [comment]
Yep, looks good to me! I think if we declare support for Django 3.2, then it will be also nice to solve #615 in this release. Especially as the fix is a one-liner (as in [this PR](https://github.com/StevenMapes/django-money/pull/1)), so Django 3.2 users will have a warning-less experience :)

> Another thing for discussion here though, it would make sense to me also drop support for Python 3.6 now as it only has 3 more months to live, and probably even less by the time we're ready to release. It makes sense to me since we're about to make a major release anyway for py-moneyed 2. Wdyt?

I'd go for as frictionless experience as possible - I think we can just make another release when we drop Python 3.6 after its EOL.

**Comment by Stranger6667** [comment]
On #615 - it surely might be a part of a different PR.

**Review by Stranger6667 — APPROVED** [review]
Feel free to squash & merge this PR once you feel it's ready :)

**Comment by benjaoming** [comment]
In case we merged this now, I wonder if we have any good ways to ensure that we don't release from `master` before #615 is fixed :)

**Comment by StevenMapes** [comment]
Yeah sure I just didn't finish the or when by browser went wrong then I
went on vacation

**Comment by antonagestam** [comment]
@StevenMapes Great, I brought in your commit here 👍

@benjaoming @Stranger6667 Unless there are other concerns, I think this should be good to go now 🙂

**Comment by Stranger6667** [comment]
I think we are good to go :)

**Comment by benjaoming** [comment]
THANKS ALL :ship: 

I just went ahead and did the honors of merging, but we should be able to release this as well.

Suggesting that we bump to 2.1 because of the backwards incompats... any other suggestions?

**Comment by antonagestam** [comment]
@benjaoming 🥳

On releasing, since these are breaking changes, doesn't that warrant a major version bump, e.g. 3.0? My plan was to prepare for further work with this PR, and follow that up with the py-moneyed upgrade (that is work in progress) in the same release. The reason I think it makes sense to have them both in 3.0 is that they are both breaking changes, and otherwise we'd have to release a 4.0 so soon after.

I'll try to find the time to finalize the [py-moneyed work](https://github.com/antonagestam/django-money/pull/1) soon so that it doesn't hold up the release! What do you think? 🙂

**Comment by benjaoming** [comment]
@antonagestam it's still only smaller breaking changes, so since we are sticking to SemVer, it's still a minor version bump with no changes to API or data models and such.

I'll go ahead and get this released now :)

I think that it might work great for you to bump py-moneyed on the major digit, but once py-moneyed 2.0 is out, we can create a django-money release that bumps to py-moneyed >=2.0 and ALSO bump the major version of django-money to 3.0 since this could be considered a breaking change for those using django-money.

That leaves a nice upgrade path, too: Upgrade to django-money 2.1 and any Python/Django versions that might need upgrading, too, _then_ upgrade py-moneyed.

**Comment by antonagestam** [comment]
@benjaoming Hmm, I'd definitely consider dropping support for Python versions as a breaking change though.

**Comment by benjaoming** [comment]
@antonagestam it's definitely a breaking change, but the way that Django and Python are being released, most projects are choosing to treat this with minor version bumps.

I have gone ahead with the release now, so we are ready for the next py-moneyed :+1: :100: 

image

**Comment by antonagestam** [comment]
@benjaoming Cool! Exciting to see things in motion! 😃

**Pull request merged**
