### PR TITLE
Fixed field lookup regression. Fixes #300

### LINKED ISSUE #300: Filter using ForeignKey field raises FieldError
I've found a bug which seems to be a regression in 0.11.1 - everything was fine in 0.11
I'm running latest stable Django (1.11.1).

So I have code such as
```python
import datetime as datetime

class MoneyTest(models.Model):
    date = models.DateTimeField()

class MoneyItemTest(models.Model):
    money =  models.ForeignKey(Purchase, on_delete=models.CASCADE)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='EUR', default=Decimal('0.0'))


# Queries
date = datetime.datetime(year=2017, month=2, day=1)
query = MoneyItemTest.objects.filter(money__date=date) # still works
query = MoneyItemTest.objects.filter(money__date__gt=date) # worked in 0.11, crashes in 0.11.1
```

The second query generates this traceback
```bash
File "\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
File "\env\lib\site-packages\djmoney\models\managers.py", line 211, in wrapper
    args, kwargs = _expand_money_kwargs(model, args, kwargs, exclusions)
File "\env\lib\site-packages\djmoney\models\managers.py", line 150, in _expand_money_kwargs
    field = _get_field(model, name)
File "\env\lib\site-packages\djmoney\models\managers.py", line 55, in _get_field
    return qs.names_to_path(parts, qs.get_meta(), True, fail_on_missing=False)[1]
File "\env\lib\site-packages\django\db\models\sql\query.py", line 1363, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'money' into field. Choices are: date, id, moneyitemtest
```

If that's of any help, I get these warnings too:
```bash
\env\lib\site-packages\djmoney\models\managers.py:58: RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.
  model = lookup_field.rel.to
\env\lib\site-packages\djmoney\models\managers.py:58: RemovedInDjango20Warning: Usage of ForeignObjectRel.to attribute has been deprecated. Use the model attribute instead.
```

Regards,
Lorcan

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by Stranger6667** [comment]
Hello @benjaoming!
Can we make a new bugfix release when this PR will be merged? I made a mistake in 813c7853a6ef0bf3e7d6d7fcb9d20d312fdb93da :(

**Comment by benjaoming** [comment]
Sure thing! I guess it's critical?

Maybe do a test that catches the err?

**Comment by Stranger6667** [comment]
Yes, it is critical :) I've added a test case - ```test_issue_300_regression``` which is based on the code originally proposed by @lmdsp.

**Comment by Stranger6667** [comment]
So, we're ready to the new release :)

**Comment by benjaoming** [comment]
Awesome, great work, release is out :tada:

**Comment by benjaoming** [comment]
Super with the test case, too!

**Comment by lmdsp** [comment]
Great, thanks again !

**Pull request merged**
