### PR TITLE
Support for Django 1.8

### PR DESCRIPTION
**Pull request by pedrorodriguesgomes**

### CODE REVIEW

**Comment by benjaoming** [comment]
Cool @pedrorodriguesgomes ! Can you confirm that Tox tests run on various platforms?

**Comment by luzfcb** [comment]
@benjaoming @jakewins Enable travis-ci for this project.

**Comment by benjaoming** [comment]
@luzfcb Yeah good luck getting a hold of @jakewins :) Haven't heard a peep for a very long time. Otherwise this would've been done a long time ago.

**Comment by edwinlunando** [comment]
Nice! I have test this PR and it runs beautifully. :)

**Comment by benjaoming** [comment]
@edwinlunando nice - as in you've run the tests? :)

**Comment by nueverest** [comment]
@edwinlunando I've update the gen_tox.bash and generated a new tox.ini  to include django 1.7, 1.8 and python 3.4 in tox tests.

You can find them here:
https://github.com/nueverest/django-money/blob/master/gen_tox.bash
https://github.com/nueverest/django-money/blob/master/tox.ini

**Comment by benjaoming** [comment]
@jakewins how about you create a django-money organization, transfer the project to that one and make a couple of people admins of this organization?

It's really not nice to have all this confusion with different forks floating around, and it would be nice to integrate Travis hooks into Github now.

**Comment by benjaoming** [comment]
@jakewins please please please :)

**Comment by edwinlunando** [comment]
@benjaoming since @jakewins did not respond, how about making a new fork?

**Comment by benjaoming** [comment]
Trying to reach @jakewins by email...

**Comment by jakewins** [comment]
@benjaoming sorry mate, hadn't seen this, I need to sort out my GH notifications. Good call on swapping to an org. I'll set up a django-money org and transfer the repo there

**Comment by jakewins** [comment]
@benjaoming done, invited you as an owner so you should have full access to things

**Comment by benjaoming** [comment]
@jakewins that's great news! I'm setting up Travis now so we can have the PRs merged quicker...

**Comment by edwinlunando** [comment]
@benjaoming do you need help with anything? I want django-money release the 1.8 support faster.

**Comment by benjaoming** [comment]
@edwinlunando sorry about the silence, I got stuck waiting for a Travis thing... I'm taking this PR hostage until there's a proper test setup... let me just log in to Travis and see....

**Comment by benjaoming** [comment]
@edwinlunando I've setup travis support so it's building now but complaining about some invalid Tox env... if you can have a look at that, that'd be great :)

https://travis-ci.org/django-money/django-money/

**Comment by benjaoming** [comment]
*I didn't set up all that travis/tox stuff, compliments to @spookylukey and @ashleyh

**Comment by orgkhnargh** [comment]
Hello, guys. I have noticed that you use custom bash script to generate `tox.ini` file. Actually it is not required since tox supports environments generation and conditional settings since version 1.8, here is docs: https://tox.readthedocs.org/en/latest/config.html#generating-environments-conditional-settings

I have spent some time before on configuring tox to generate all the environments itself (which is basically what `gen_tox.bash` does) during work on [this](https://github.com/carljm/django-model-utils/pull/159). Are you interested in updating your tox configuration in such way?

**Comment by benjaoming** [comment]
@orgkhnargh sure, I think it might also need to have django 1.8 included as this PR does not change tox settings.

**Comment by edwinlunando** [comment]
@orgkhnargh ah yes, the bash script is legacy issues. I will try to fix it. Thanks for the inputs.

**Comment by enono78** [comment]
Go ahead guys! Let's support Django 1.8 :+1:

**Pull request merged**
