### PR TITLE
Update builds

### PR DESCRIPTION
**Pull request by Stranger6667**
Added builds for isort and flake8. Also, I've clarified `patched_convert_money` fixture.

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks for this, merging right away!

**Comment by benjaoming** [comment]
Hmm, one thing, maybe a little nit-picky...

> flake8 installed: Django==1.9.2,django-money==0.7.7,flake8==2.5.4,mccabe==0.4.0,pep8==1.7.0,py-moneyed==0.6.0,pyflakes==1.0.0,wheel==0.24.0

> isort-check installed: Django==1.9.2,django-money==0.7.7,isort==4.2.2,py-moneyed==0.6.0,wheel==0.24.0

Maybe it's better to merge the checks into one "lint" env? That way, we avoid the double-work of setting up identical Tox envs.

**Comment by Stranger6667** [comment]
Done! :)

**Comment by Stranger6667** [comment]
Travis-related error [https://travis-ci.org/django-money/django-money/jobs/109545213](here)

**Comment by benjaoming** [comment]
Rebuilding!

**Comment by benjaoming** [comment]
Thanks for addressing the comment!

**Comment by Stranger6667** [comment]
Thank you, @benjaoming :)

**Pull request merged**
