### PR TITLE
Change import of convert_money

### PR DESCRIPTION
**Pull request by Stranger6667**
It was possible to ``from djmoney.money import Money`` without  `djmoney.contrib.exchange` in INSTALLED_APPS

### CODE REVIEW

**Comment by Stranger6667** [comment]
I'll cherry-pick changes to master

**Comment by Stranger6667** [comment]
I forgot about the changelog, I'll add it directly to 0.13.x branch

**Comment by benjaoming** [comment]
Already did that @Stranger6667 !

**Comment by Stranger6667** [comment]
Thanks :)

**Pull request merged**
